permissionset 50298 "TAC-POOL-FINANCE"
{
    Assignable = true;
    Caption = 'Pool Finance';
    // Full read/write on the pool tables and execute on every engine object,
    // incl. close (50273), adjust/expense (50274/50275), and GL posting (50279).
    // Extension fields on Customer (50240) / Sales Invoice Header (50241) ride
    // on base-table tabledata permission (design §10.1).
    Permissions = tabledata "TAC Pool Week"=RIMD,
        tabledata "TAC Pool Trans Type"=RIMD,
        tabledata "TAC Pool Charge Template"=RIMD,
        tabledata "TAC Pool Chg Tmpl Grade Excl"=RIMD,
        tabledata "TAC Grower GL Override"=RIMD,
        tabledata "TAC Pool Setup"=RIMD,
        tabledata "TAC Pool Group Header"=RIMD,
        tabledata "TAC Pool"=RIMD,
        tabledata "TAC Pool Ledger Entry"=RIMD,
        tabledata "TAC Pool Payment Header"=RIMD,
        tabledata "TAC Pool Adjustment"=RIMD,
        tabledata "TAC Pool Expense Header"=RIMD,
        tabledata "TAC Pool Expense Detail"=RIMD,
        tabledata "TAC Pool Grower Charge"=RIMD,
        tabledata "TAC Pool Reconciliation"=RIMD,
        tabledata "TAC Pool Recon Line"=RIMD,
        page "TAC Pool Group List"=X,
        page "TAC Pool Group Card"=X,
        page "TAC Pool Subpage"=X,
        page "TAC Pool Ledger Entries"=X,
        page "TAC Pool Adjustment"=X,
        page "TAC Pool Expense"=X,
        page "TAC Pool Expense Detail Sub"=X,
        page "TAC Pool Trans Types"=X,
        page "TAC Pool Charge Template"=X,
        page "TAC Pool Weeks"=X,
        page "TAC Grower GL Overrides"=X,
        page "TAC Pool Grower Charges"=X,
        page "TAC Pool Setup"=X,
        page "TAC Pool Charge Preview"=X,
        page "TAC Pool Reconciliation List"=X,
        page "TAC Pool Reconciliation Card"=X,
        page "TAC Pool Recon Lines"=X,
        codeunit "TAC Pool Charge Engine"=X,
        codeunit "TAC Pool Prod Order Post"=X,
        codeunit "TAC Pool Consignment Post"=X,
        codeunit "TAC Pool Group Close"=X,
        codeunit "TAC Pool Adjustment Post"=X,
        codeunit "TAC Pool Expense Post"=X,
        codeunit "TAC Pool Dimension Mgt"=X,
        codeunit "TAC Pool Grower Mgt"=X,
        codeunit "TAC Pool Consumption Grower"=X,
        codeunit "TAC Pool Vendor Grower Sync"=X,
        codeunit "TAC Pool Post Diagnostic"=X,
        codeunit "TAC Pool Preview"=X,
        codeunit "TAC Pool Reconciliation"=X,
        codeunit "TAC Pool Subscribers"=X,
        codeunit "TAC Pool Install"=X,
        codeunit "TAC Pool GL Posting"=X,
        report "TAC Pool Return"=X,
        report "TAC Pool Group Summary"=X,
        report "TAC Open Pool Balance"=X;
}
